export const DIALOG_NEGATIVE_RESPONSE = "DECLINED"
export const DIALOG_POSITIVE_RESPONSE = "CONFIRM"
export const DELETE_CONFIRMATION_MESSAGE = "Note titled %s will be deleted"
export const SAVE_CONFIRMATION_MESSAGE = "Note titled %s will be saved"
export const SAVE_SUCCESS = "Note saved successfully"
export const DELETE_SUCCESS = "Note deleted successfully"
export const NOTES_SNACKBAR_DURATION = 2500
export const EMPTY_FIELD_MESSAGE = "This field cannot be empty"
export const ERROR_MESSAGE = "Some error occurred"
export const PASSWORD_NOT_MATCH = "Confirm password does not match"
export const INVALID_EMAIL = "Invalid email"
export const SHORT_PASSWORD_MESSAGE = "Password should be of atleast 8 characters"
export const MIN_PASSWORD_LENGTH = 8
export const SIGN_OUT_CONFIRMATION = "You will be signed out of this session"